---
name: BuildAndPublish

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Build and publish
        run: .\build.ps1
        shell: powershell
        env:
          CHOCOPUSHKEY: ${{ secrets.CHOCOPUSHKEY }}
        continue-on-error: true
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: yor
          path: .\*.nupkg
